stages:
    - build

create_image:
    stage: build
    script:
        - echo "ssh -i /tmp/.ssh_key_temp.$CI_PROJECT_ID  \$@" > /tmp/.ssh_exec.$CI_PROJECT_ID
        - export GIT_SSH=/tmp/.ssh_exec.$CI_PROJECT_ID
        - echo "$github_key"
        - touch /tmp/.ssh_key_temp.$CI_PROJECT_ID
        - chmod 700 /tmp/.ssh_key_temp.$CI_PROJECT_ID
        - echo "$github_key" >> /tmp/.ssh_key_temp.$CI_PROJECT_ID
        - git remote add github $GIT_HUB_URL
        - git push github
        - git remote remove github
        - rm /tmp/.ssh_key_temp.$CI_PROJECT_ID
        - rm /tmp/.ssh_exec.$CI_PROJECT_ID
        