stages:
    - build

create_image:
    stage: build
    script:
        - bash -c "git remote remove github; exit 0"
#        - echo "ssh -i /tmp/.ssh_key_temp.$CI_PROJECT_ID  \$@" > /tmp/.ssh_exec.$CI_PROJECT_ID
#        - chmod 700 /tmp/.ssh_exec.$CI_PROJECT_ID
#        - export GIT_SSH=/tmp/.ssh_exec.$CI_PROJECT_ID
#        - touch /tmp/.ssh_key_temp.$CI_PROJECT_ID
#        - chmod 700 /tmp/.ssh_key_temp.$CI_PROJECT_ID
#        - echo "$github_key" >> /tmp/.ssh_key_temp.$CI_PROJECT_ID
        - git status
        - git remote add github $GIT_HUB_URL
        - git config --global user.email "noreply@teamwork.net"
        - git config --global user.name "TeamWork"        
#        - git pull github master

        - git checkout master
        - git pull origin master
        - git status
        - bash -c "git push --force github master | grep -v github.com"
        - git remote remove github
#        - rm /tmp/.ssh_key_temp.$CI_PROJECT_ID
#        - rm /tmp/.ssh_exec.$CI_PROJECT_ID